name: SmartRestart
version: 0.1a
description: Privodes a smarter way to restart the server.
author: psygate
main: com.psygate.smartrestart.SmartRestart
database: false
commands:
    srtelemetry:
        description: Provides telemetry about the server state.
        aliases: srel
        permission: smartrestart.telemetry
        usage: /srel
    srforcelimit:
        description: Provides telemetry about the server state.
        aliases: srfl
        permission: smartrestart.forcelimit
        usage: /srfl
    srforcetick:
        description: Provides telemetry about the server state.
        aliases: srft
        permission: smartrestart.forcetick
        usage: /srft
    srreload:
        description: Reloads the configuration.
        aliases: srrl
        permission: smartrestart.reload
        usage: /srrl
    srrestart:
        description: Restarts the server per request.
        permission: smartrestart.restart
        usage: /srrestart


permissions:
    smartrestart.telemetry:
        description: Allows access to the telemetry command.
        default: op
    smartrestart.forcelimit:
        description: Allows access to the force limit command.
        default: op
    smartrestart.forcetick:
        description: Allows access to the force tick command.
        default: op
    smartrestart.notifications:
        description: Will turn on verbose notification for that person.
        default: op
    smartrestart.restart:
        description: Will restart the server.
        default: op
        